spring:
  datasource:
    url: jdbc:mysql://localhost:3306/traffic
    username: dooho
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    open-in-view: true
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    show-sql: true
  sql.init.mode: always
  messages:
    encoding: UTF-8


elasticsearch:
  host: 127.0.0.1
  port: 9200